name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install just
      uses: extractions/setup-just@v2
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install 3.13
      
    - name: Install Python dependencies
      run: just py-install
      
    - name: Run ruff linting
      run: just py-lint
      
    # TODO: Fix test configuration and re-enable
    # - name: Run Python tests
    #   run: just py-test

  typescript-lint-and-typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install just
      uses: extractions/setup-just@v2
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install console dependencies
      run: just console-install
      
    - name: Lint console
      run: just console-lint
      
    - name: Type check console
      run: just console-typecheck
      
    - name: Build console
      run: just console-build

  api-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install just
      uses: extractions/setup-just@v2
      
    - name: Setup Node.js for Spectral
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Spectral
      run: npm install -g @stoplight/spectral-cli
      
    - name: Validate OpenAPI spec
      run: just api-validate